version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - cd src && npm install
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm test
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./coverage 
      - rm -rf ./node_modules
      - rm -rf ./tests
      - rm -rf .npmignore
      
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - cd ..
      - rm -rf ./public
      - rm -rf README.md
      - rm -rf LICENSE
      - rm -rf .gitignore 
      - aws cloudformation package --template template.yaml --s3-bucket urlshortnerbucket --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  #discard-paths: yes
  files:
    - '**/*'
  
  

