apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: urlshortner
  annotations:
    github.com/project-slug: memoverflow/urlshortner
spec:
  type: other
  lifecycle: unknown
  owner: guests
